# Generated by Django 4.2.30 on 2026-09-08 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('class_name', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('qr_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('qr_enabled', models.BooleanField(default=True)),
                ('attendance_status', models.CharField(choices=[('not.boarded', 'Not Boarded'), ('waiting', 'Waiting'), ('picked_up', 'Picked Up'), ('on_bus', 'On Bus'), ('dropped', 'Dropped'), ('absent', 'Absent')], default='not.boarded', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='fleet.bus')),
                ('assigned_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='routes.route')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_student',
                'ordering': ['class_name', 'full_name'],
            },
        ),
    ]
