# Generated by Django 4.2.30 on 2026-09-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('picked_up', 'Picked Up'), ('on_bus', 'On Bus'), ('dropped', 'Dropped'), ('absent', 'Absent')], default='waiting', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('qr', 'QR'), ('manual', 'Manual')], default='qr', max_length=10)),
                ('trip_stage', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='pickup', max_length=10)),
            ],
            options={
                'db_table': 'attendance_record',
                'ordering': ['-timestamp'],
            },
        ),
    ]
