# Generated by Django 4.2.30 on 2026-09-08 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('responded', 'Responded'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('escalation_level', models.PositiveIntegerField(default=0)),
                ('escalation_timer', models.PositiveIntegerField(default=0, help_text='Seconds before next escalation')),
                ('primary_contact', models.CharField(blank=True, max_length=20)),
                ('secondary_contact', models.CharField(blank=True, max_length=20)),
                ('authority_contact', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='fleet.bus')),
            ],
            options={
                'db_table': 'safety_sos_alert',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('speed', 'Speed Limit'), ('harsh_brake', 'Harsh Braking'), ('route_deviation', 'Route Deviation'), ('stop_violation', 'Stop Violation'), ('general', 'General')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_alerts', to='fleet.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'safety_driver_alert',
                'ordering': ['-created_at'],
            },
        ),
    ]
