# Generated by Django 4.2.30 on 2026-09-08 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_model', models.CharField(default='ST-901A', max_length=50)),
                ('provider', models.CharField(choices=[('sinotrack', 'SinoTrack'), ('other', 'Other')], default='sinotrack', max_length=20)),
                ('device_identifier', models.CharField(help_text='SinoTrack device ID or serial number', max_length=100, unique=True)),
                ('imei', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='active', max_length=15)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bus', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_device', to='fleet.bus')),
            ],
            options={
                'db_table': 'gps_device',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteDeviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviation_distance', models.DecimalField(decimal_places=2, help_text='Meters from route', max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_deviations', to='fleet.bus')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route')),
            ],
            options={
                'db_table': 'gps_route_deviation',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recorded_at', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_history', to='fleet.bus')),
                ('gps_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gps.gpsdevice')),
            ],
            options={
                'db_table': 'gps_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bus', 'recorded_at'], name='gps_history_bus_id_42403c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('gps_status', models.CharField(blank=True, default='online', max_length=10)),
                ('gsm_signal', models.CharField(blank=True, default='good', max_length=10)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='fleet.bus')),
                ('gps_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='gps.gpsdevice')),
            ],
            options={
                'db_table': 'gps_bus_location',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bus', '-recorded_at'], name='gps_bus_loc_bus_id_13eccb_idx'), models.Index(fields=['recorded_at'], name='gps_bus_loc_recorde_512681_idx')],
            },
        ),
    ]
